EternalKingdom/src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CityRepository::class)
 */
class City
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToOne(targetEntity=Lord::class, inversedBy="city", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $lord;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $grid;

    /**
     * @ORM\Column(type="smallint")
     */
    private $remainingTurns = 100;

    /**
     * @ORM\Column(type="smallint")
     */
    private $wastedTurns = 0;

    /**
     * @ORM\OneToMany(targetEntity=Storage::class, mappedBy="city", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $storages;

    /**
     * @ORM\OneToMany(targetEntity=BuiltBuildings::class, mappedBy="city", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $builtBuildings;

    /**
     * @ORM\Column(type="boolean")
     */
    private $recruiting = true;

    /**
     * @ORM\ManyToOne(targetEntity=Constructions::class)
     */
    private $constructionProject;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $projectLevel;


    public function __construct()
    {
        $this->storages = new ArrayCollection();
        $this->builtBuildings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLord(): ?Lord
    {
        return $this->lord;
    }

    public function setLord(Lord $lord): self
    {
        $this->lord = $lord;

        return $this;
    }

    public function getGrid(): ?string
    {
        return $this->grid;
    }

    public function setGrid(string $grid): self
    {
        $this->grid = $grid;

        return $this;
    }

    public function getRemainingTurns(): ?int
    {
        return $this->remainingTurns;
    }

    public function setRemainingTurns(int $remainingTurns): self
    {
        $this->remainingTurns = $remainingTurns;

        return $this;
    }

    public function getWastedTurns(): ?int
    {
        return $this->wastedTurns;
    }

    public function setWastedTurns(int $wastedTurns): self
    {
        $this->wastedTurns = $wastedTurns;

        return $this;
    }

    /**
     * @return Collection|Storage[]
     */
    public function getStorages(): Collection
    {
        return $this->storages;
    }

    public function addStorage(Storage $storage): self
    {
        if (!$this->storages->contains($storage)) {
            $this->storages[] = $storage;
            $storage->setCity($this);
        }

        return $this;
    }

    public function removeStorage(Storage $storage): self
    {
        if ($this->storages->removeElement($storage)) {
            // set the owning side to null (unless already changed)
            if ($storage->getCity() === $this) {
                $storage->setCity(null);
            }
        }

        return $this;
    }

    public function getStorageCount(string $resourceName) : int //TODO : Maybe optimize ?
    {
        foreach($this->storages as $storage) 
        {
            if($storage->getResource()->getName() !== $resourceName) continue;
            return $storage->getAmount();
        }
        return 0;
    }

    public function getPopulationCount() : int
    {
        $count = 0;
        foreach($this->storages as $storage) 
        {
            if($storage->getResource()->getResourceType() !== 'population') continue;
            $count += $storage->getAmount();
        }
        return $count;
    }

    /**
     * @return Collection|BuiltBuildings[]
     */
    public function getBuiltBuildings(): Collection
    {
        return $this->builtBuildings;
    }

    public function addBuiltBuilding(BuiltBuildings $builtBuilding): self
    {
        if (!$this->builtBuildings->contains($builtBuilding)) {
            $this->builtBuildings[] = $builtBuilding;
            $builtBuilding->setCity($this);
        }

        return $this;
    }

    public function removeBuiltBuilding(BuiltBuildings $builtBuilding): self
    {
        if ($this->builtBuildings->removeElement($builtBuilding)) {
            // set the owning side to null (unless already changed)
            if ($builtBuilding->getCity() === $this) {
                $builtBuilding->setCity(null);
            }
        }

        return $this;
    }

    public function getBuildingLevel(string $buildingName)
    {
        foreach($this->builtBuildings as $builtBuilding) 
        {
            if($builtBuilding->getBuilding()->getName() !== $buildingName) continue;
            return $builtBuilding->getLevel();
        }
        return 0;
    }

    public function isRecruiting(): ?bool
    {
        return $this->recruiting;
    }

    public function setRecruiting(bool $recruiting): self
    {
        $this->recruiting = $recruiting;

        return $this;
    }

    public function getConstructionProject(): ?Constructions
    {
        return $this->constructionProject;
    }

    public function setConstructionProject(?Constructions $constructionProject): self
    {
        $this->constructionProject = $constructionProject;

        return $this;
    }

    public function getProjectLevel(): ?int
    {
        return $this->projectLevel;
    }

    public function setProjectLevel(?int $projectLevel): self
    {
        $this->projectLevel = $projectLevel;

        return $this;
    }
   

}

EternalKingdom/src/Controller/CityController.php
<?php

// src/Controller/CityController.php
namespace App\Controller;

use App\Entity\Lord;
use App\Model\SwapCandidate;
use App\Model\Tile;
use App\Service\GridManager;
use App\Service\CityManager;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/*
 * Conseil from Nawadoo
 * Côté serveur il "suffit" d'envisager tous les cas de figure (paramètre manquant, paramètre non numérique, etc)
 * Et veiller à ne pas avoir de paramètres contradictoires. Par exemple pour vérifier un stock il est inutile de transmettre le montant en paramètre, puisqu'on va le récupérer côté serveur de toutes façons
 * C'est un peu toujours les mêmes contrôles
 * Si tu veux commencer doucement, tu peux faire un envoi de formulaire classique qui actualise toute la page, à l'ancienne. Et dans un second temps, remplacer ça par de l'ajax
 */

/**
 * CityController will display the City page
 * It permits to access the Match3 to increase resource stocks & population
 * and permits to make new buildings and improve the army.
 * @package App\Controller
 */
class CityController extends AbstractController
{
    //Managers
    private $gridManager;
    private $cityManager;

    /**
     * CityController constructor.
     * @param GridManager $gridManager
     * @param CityManager $cityManager
     */
    public function __construct(GridManager $gridManager, CityManager $cityManager)
    {
        $this->gridManager = $gridManager;
        $this->cityManager = $cityManager;
    }

    /**
     * City index page
     * @Route("/city/{id}")
     * @param int $id
     * @return Response
     */
    public function city(int $id): Response
    {
        return $this->GenerateCommonCityPageResponse($id, 'City/index.html.twig');
    }

    /**
     * @Route("/city/{id}/chooseConstruction")
     * @param int $id
     * @return Response
     */
    public function chooseConstruction(int $id): Response
    {
        $lordRepository = $this->GetDoctrine()->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $this->InitCityGrid($lord);
        $allParameters = [
            'lord' => $lord,
            'maxAmounts' => $this->cityManager->getMaxStorages($lord->getCity()),
            'constructionProjects' =>$this->cityManager->getDisplayedProjects($lord->getCity())
        ];
        return $this->render('City/optionChooseBuilding.html.twig', $allParameters);
    }

     /**
     * Request needs the constructionName !
     * @Route("/city/{id}/startConstruction/{name}_{level}")
     * @param int $id
     * @param string $name
     * @param int $level
     * @return Response
     */
    public function startConstruction(int $id, string $name, int $level): Response
    {
        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);

        if ($this->cityManager->startConstruction($lord->getCity(), $name, $level))
        {
            $entityManager->flush();
            return $this->redirectToRoute("app_city_city", ['id' => $id]);
        }

        return $this->redirectToRoute("app_city_chooseconstruction", ['id' => $id]);
    }

    /**
     * @Route("/city/{id}/cancelConstruction")
     * @param int $id
     * @return Response
     */
    public function cancelConstruction(int $id): Response
    {
        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);

        if ($this->cityManager->cancelConstruction($lord->getCity()))
        {
            $entityManager->flush();
        }
        return $this->redirectToRoute("app_city_city", ['id' => $id]);
    }

    /**
     * @Route("/city/{id}/chooseSoldierUpgrade")
     * @param int $id
     * @return Response
     */
    public function chooseSoldierUpgrade(int $id): Response
    {
        $lordRepository = $this->GetDoctrine()->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $this->InitCityGrid($lord);
        $allParameters = [
            'lord' => $lord,
            'maxAmounts' => $this->cityManager->getMaxStorages($lord->getCity()),
            'upgradeSchemas' => $this->cityManager->getDisplayedConversionSchemas($lord->getCity(), 'army')
        ];
        return $this->render('City/optionUpgradeSoldier.html.twig', $allParameters);
    }

    /**
     * Request needs the producedResourceName !
     * @Route("/city/{id}/upgradeSoldier/{resourceName}", methods={"POST"}))
     * @param Request $request
     * @param int $id
     * @param string $resourceName
     * @return Response
     */
    public function upgradeSoldier(Request $request, int $id, string $resourceName): Response
    {
        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $amount = $request->request->get('count');

        if ($this->cityManager->convertResources($lord->getCity(), $resourceName, $amount))
        {
            $entityManager->flush();
        }
        return $this->redirectToRoute("app_city_choosesoldierupgrade", ['id' => $id]);
    }



    /**
     * Request needs the producedResourceName !
     * @Route("/city/{id}/toggleRecruitment"))
     * @param int $id
     * @return Response
     */
    public function toggleRecruitment(int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $this->cityManager->toggleRecruitment($lord->getCity());
        $entityManager->flush();
        return $this->redirectToRoute("app_city_choosesoldierupgrade", ['id' => $id]);
    }

    /**
     * @Route("/city/{id}/chooseResourceConversion")
     * @param int $id
     * @return Response
     */
    public function chooseResourceConversion(int $id): Response
    {
        $lordRepository = $this->GetDoctrine()->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $this->InitCityGrid($lord);

        $allParameters = [
            'lord' => $lord,
            'maxAmounts' => $this->cityManager->getMaxStorages($lord->getCity()),
            'conversionSchemas' =>$this->cityManager->getDisplayedConversionSchemas($lord->getCity(), 'resource')
        ];
        return $this->render('City/optionConvertResources.html.twig', $allParameters);
    }

    /**
     * Request needs the producedResourceName !
     * @Route("/city/{id}/convertResources/{resourceName}", methods={"POST"}))
     * @param Request $request
     * @param int $id
     * @param string $resourceName
     * @return Response
     */
    public function convertResources(Request $request, int $id, string $resourceName): Response
    {
        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $amount = $request->request->get('count');

        if ($this->cityManager->convertResources($lord->getCity(), $resourceName, $amount))
        {
            $entityManager->flush();
        }

        return $this->redirectToRoute("app_city_chooseresourceconversion", ['id' => $id]);
    }

    /**
     * @Route("/city/{id}/chooseGeneralName")
     * @param int $id
     * @return Response
     */
    public function chooseGeneralName(int $id): Response
    {
        return $this->GenerateCommonCityPageResponse($id, 'City/optionRecruitGeneral.html.twig');
    }

    /**
     * Request needs the producedResourceName !
     * @Route("/city/{id}/recruitGeneral", methods={"POST"}))
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function recruitGeneral(Request $request, int $id): Response
    {
        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);
        $name = $request->request->get('name');

        if ($this->cityManager->recruitGeneral($lord->getCity(), $name))
        {
            $entityManager->flush();
            return $this->redirectToRoute("app_map_map", ['id' => $id]);
        }
        return $this->redirectToRoute("app_city_city", ['id' => $id]);   
    }


    /**
     * Request needs the CitizenId !
     * @Route("/city/{id}/convertCitizen", methods={"POST"})
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function ConvertCitizen(Request $request, int $id): Response
    {
        $response = new Response();
        $statusCode = Response::HTTP_FORBIDDEN;

        // TODO Verify if the logged player owns this lord!
        $entityManager = $this->getDoctrine()->getManager();
        $lordRepository = $entityManager->GetRepository(Lord::class);
        $lord = $lordRepository->find($id);

        $payload = json_decode($request->request->get("json"), true);
        $citizenId = $payload['citizenId'];

        if ($this->cityManager->convertCitizen($lord->getCity(), $citizenId))
        {
            $statusCode = Response::HTTP_OK;
            $entityManager->flush();
        }

        $response->setStatusCode($statusCode);

        return $response;
    }

    /**
     * Request needs the swap coordinates from client JSON paylood !
     * @Route("/city/{id}/swapTiles", methods={"POST"})

EternalKingdom/templates/City/city.html.twig
{# Templates/City/optionUpgradeSoldier.html.twig #}
{# City skeleton (It displays army, city options, resource stocks, grid and logs) #}

{% extends 'base.html.twig' %}

{% block title %}
    - Capitale
{% endblock %}

{% block stylesheets %}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="{{ asset('js/gameGrid.js') }}" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}

{% block content %}
    <p class = "ServerData" data-grid="{{ lord.city.grid }}" data-lordId="{{ lord.id }}"></p>
    <ul class="resources rescity">
        {% for resourceName in ['wheat', 'gold', 'wood', 'iron', 'lin', 'horse'] %}
            {% set maxAmount = maxAmounts[resourceName] %}
            <li>
                <div
                        class="res"
                        onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('resources.'~resourceName~'.name') | trans([], 'City') }}</h1><div class=\'infos max\'>max : {{ maxAmount }}</div>{{ ('resources.'~resourceName~'.desc') | trans([], 'City') }}</div></div></div>')"
                        onmouseout="mt.js.Tip.hide()"
                >
                    <div class="resp">
                        <span class="n" data-max="{{ maxAmount }}">{{ lord.city.storageCount(resourceName) }}</span>
                    </div>
                    <img src="{{ asset('img/icons/res_'~resourceName~'.png') }}" alt="" class="" />
                </div>
            </li>
        {% endfor %}
    </ul>

    <h1 class="city">{{ lord.city.name }}</h1>
    <div class="h1">
        <div class="h1mid">
            <div class="h1bottom">
                <table class="city">
                    <tbody>
                    <tr>
                        <td>
                            <!-- UNITS -->
                            <div class="box1 unitsgar">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        <h2 class="h2a">{{ 'header.units' | trans([], 'City') }}</h2>
                                        {% set displayedArmy = false %}
                                        {% for unit in ['soldier', 'pikeman', 'archer', 'horseman', 'knight', 'mountedArcher', 'paladin', 'catapult', 'ballista'] %}
                                            {% if lord.city.storageCount(unit)>0 %}
                                                {% set displayedArmy = true %}
                                            {% endif %}
                                        {% endfor %}

                                        {% if displayedArmy %}
                                            <ul class = "army items">                  
                                                {% for unit in ['soldier', 'pikeman', 'archer', 'horseman', 'knight', 'mountedArcher', 'paladin', 'catapult', 'ballista'] %}
                                                    <li>
                                                        <div class="item {% if lord.city.storageCount(unit)==0 %} disable{% endif %}"
                                                            onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('units.'~unit~'.name') | trans([], 'City') }}</h1>{{ ('units.'~unit~'.desc') | trans([], 'City') }}</div></div></div>')"
                                                            onmouseout="mt.js.Tip.hide()">
                                                            <img src="/img/icons/u_{{ unit }}.png" alt="">
                                                            <span class="number">{{ lord.city.storageCount(unit) }}</span>                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                        <p class="nothing {% if displayedArmy %}hidden{% endif %}">
                                            {{ 'messages.noArmy' | trans([], 'City') }}
                                        </p>
                                            
                                            <div class="clear"></div>
                                    </div>
                                </div>
                            </div>

                            <!-- OPTIONS -->
                            <div class="box1">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        <h2 class="h2d">{% block cityOptionsTitle %}{% endblock %}</h2>
                                        {% block cityOption %}
                                        {% endblock %}
                                    </div>
                                </div>
                            </div>

                            <!-- BUILDINGS -->
                            <div class="box1">
                                <div class="box1bottom">
                                    <div class="box1bg">
                                        <h2 class="h2d">{{ 'header.buildings' | trans([], 'City') }}</h2>
                                        <ul class="listbuildings">
                                            {% if lord.city.builtBuildings|length > 0 %}
                                                {% for builtBuilding in lord.city.builtBuildings %}
                                                    {% include 'City/Components/building.html.twig' with {'builtBuilding': builtBuilding} %}
                                                {% endfor %}
                                            {% else %}
                                                <div class="clear"></div>
                                                <p class="nothing">
                                                    {{ 'messages.noWorker' | trans([], 'City') }}
                                                </p>
                                            {% endif %}
                                        </ul>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>
                        </td>

                        <td class="right">
                            <div class="box2">
                                <div class="box2bottom">
                                    <div class="box2bg">
                                        <h2 class="h2e cut">{{ 'header.population' | trans([], 'City') }} ({{ lord.city.populationCount }}) </h2>
                                        <ul class="population items">
                                            {% for jobName in ['farmer', 'lumberjack', 'worker', 'merchant', 'recruiter', 'citizen'] %}
                                                <li>
                                                <div
                                                        class="item {% if lord.city.storageCount(jobName)==0 %} disable {% endif %}"
                                                        onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ ('jobs.'~jobName~'.name') | trans([], 'City') }}</h1>{{ ('jobs.'~jobName~'.desc') | trans([], 'City') }}</div></div></div>')"
                                                        onmouseout="mt.js.Tip.hide()"
                                                >
                                                    <img src="{{ asset('img/icons/people_'~jobName~'.gif') }}" alt="" />
                                                    <span class="number">{{ lord.city.storageCount(jobName) }}</span>
                                                </div>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                        <div class="clear"></div>
                                    </div>
                                </div>
                            </div>

                            <div>
                                <script type="text/javascript">
                                    function wrongMessage() {
                                        alert("{{ 'messages.forbiddenSwap' | trans([], 'City') }}");
                                    }
                                </script>
                                <div class="puzzle">
                                    <div class="infos" id="turns">
                                                                        <span
                                                                                id="counter"
                                                                                onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'>{{ 'messages.wastedTurns' | trans([], 'City') }}<b>1/21</b></div></div></div>')"
                                                                                onmouseout="mt.js.Tip.hide()"
                                                                        >
                                                                            {{ lord.city.remainingTurns }}
                                                                        </span>
                                        {{ 'messages.remainingTurns' | trans([], 'City') }} :
                                    </div>
                                    <div id="puzzleframe">
                                        <canvas id="puzzleCanvas"></canvas>
                                        <canvas id="frontCanvas"></canvas>
                                        <a class="puzzleturns disable">
                                            Oh ben c'est con t'as</br>
                                            plus de <img src="/img/icons/small/res_rec.gif"> <b>tours</b> !
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        // mt.js.Tip.exclude("puzzle");
    </script>

    <div class="log">
        <h3>{{ 'header.logs' | trans([], 'City') }}</h3>
        <div class="teml">
            <ul>
            </ul>
        </div>
    </div>
{% endblock %}

EternalKingdom/templates/City/index.html.twig
{# Templates/City/optionUpgradeSoldier.html.twig #}
{# City index (no options has been selected - lighter to load since it doesn't to compute any options data) #}

{% extends 'City/city.html.twig' %}

{% trans_default_domain 'City' %}

{% block cityOptionsTitle %}
	{{ 'header.actions' | trans }}
{% endblock %}

{% block cityOption %}
	<div class="contactions">
		{% if lord.city.constructionProject != null %}
			{% set projectName = lord.city.constructionProject.name %}
			{% set projectType = lord.city.constructionProject.constructionType %}
			{% set remainingHammers = lord.city.storageCount('remainingHammers') %}
			<div class="build">
				<p class="firstp">{{ 'messages.pendingConstruction.message' | trans }}
					<b 
						onmouseover="mt.js.Tip.show(this,'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ (projectType~'s.'~projectName~'.name') | trans([], 'City') }}</h1>{{ (projectType~'s.'~projectName~'.desc') | trans([], 'City') }}</div></div></div>')" 
						onmouseout="mt.js.Tip.hide()">
						{{ (projectType~'s.'~projectName~'.name') | trans }}
					</b>
					(<strong>{{ remainingHammers }}</strong> <img src="{{ asset('img/icons/icon_hammer.gif')}}" alt="Hammer Icon"> {{ 'messages.pendingConstruction.remaining' | trans }})
				</p>
			</div>
		{% endif %}

		{% set actionAvailable = false %}
		<ul class="actions">
			{% if lord.city.getStorageCount('worker') > 0 %}
				<li>
					{% set spanName = ('messages.build.start' | trans) %}
					{% set actionAvailable = true %}
					{% if lord.city.constructionProject != null %}
						{% set spanName = ('messages.build.list' | trans) %}
					{% endif %}
					<div onclick="document.location = '/city/{{ app.request.get('id') }}/chooseConstruction'">
						<img src="{{ asset('img/icons/a_build.png') }}" alt="Build Action">
						<span>{{ spanName }}</span>
					</div>
				</li>
			{% endif %}
			{% if lord.city.constructionProject != null %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/{{ app.request.get('id') }}/cancelConstruction'">
						<img src="{{ asset('img/icons/a_nobuild.png') }}" alt="Cancel Construction Action">
						<span>{{ 'messages.build.cancel' | trans }}</span>
					</div>
				</li>
			{% endif %}
			{% if lord.city.buildingLevel('barracks') > 0 %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/{{ app.request.get('id') }}/chooseSoldierUpgrade'">
						<img src="{{ asset('/img/icons/a_sold.png') }}" alt="Upgrade Units Action">
						<span>{{ 'header.soldierOptions' | trans }}</span>
					</div>
				</li>
				{% endif %}
			{% if lord.city.buildingLevel('cauldron') > 0 or lord.city.buildingLevel('butcher') > 0 or lord.city.buildingLevel('factory') > 0 %}
				{% set actionAvailable = true %}
				<li>
					<div onclick="document.location = '/city/{{ app.request.get('id') }}/chooseResourceConversion'">
						<img src="{{ asset('/img/icons/a_resconvert.png') }}" alt="Convert Resources Action">
						<span>{{ 'header.convertResources' | trans }}</span>
					</div>
				</li>
			{% endif %}
			{% set generalCount = 0 %}{# TODO Use lord.generals|length #}
			{% if lord.city.buildingLevel('headquarters') > 0 and generalCount < lord.city.buildingLevel('headquarters') %}
				{% set actionAvailable = true %}
				<li onmouseover="mt.js.Tip.show(this,
						'<div class=\'tiptop\'><div class=\'tipbottom\'><div class=\'tipbg\'><h1>{{ 'header.recruitGeneral' | trans }}</h1><strong class=\'wip\'>{{ 'messages.comingSoon' | trans([], "Common") }}</strong></br>{{ 'messages.recruitGeneral.desc' | trans }}<strong>{{ 50 * 2**generalCount }}</strong> <img src=\'{{ asset('img/icons/small/res_gold.gif') }}\'/>.</div></div></div>')"
					onmouseout="mt.js.Tip.hide()"
					class="disable"
				>
					<div onclick="document.location = '/city/{{ app.request.get('id') }}/chooseGeneralName';">
						<img src="{{ asset('/img/icons/a_gen.png') }}" alt="Recruit General Action">
						<span>{{ 'header.recruitGeneral' | trans }}</span>
					</div>
				</li>
			{% endif %}
		</ul>
		{% if actionAvailable == false %}
			<p class="nothing">
				{{ 'messages.noAction' | trans }}
			</p>
		{% endif %}
		<div class="clear">
		</div>
	</div>
{% endblock %}

EternalKingdom/templates/City/optionChooseBuilding.html.twig
{# Templates/City/optionChooseBuilding.html.twig #}
{# City option which permits to start a building project #}

{% extends 'City/city.html.twig' %}

{% block cityOptionsTitle %}
	{{ 'header.build' | trans([], 'City') }}
{% endblock %}

{% block cityOption %}
<ul class="buildings">
	{% for buildingProject in constructionProjects %}
		{% include 'City/Components/buildingProject.html.twig' with {'buildingProject': buildingProject} %}
	{% endfor %}
</ul>
<div class="clear"></div>
<a href="/city/{{ app.request.get('id') }}" class="button">{{ 'messages.back' | trans([], 'City') }}</a>
{% endblock %}